// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfrndyryrvrrlvqfcqvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmcm5keXJ5cnZycmx2cWZjcXZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1ODU4MTIsImV4cCI6MjA3MjE2MTgxMn0.UySk_Wz0Uk-axAiNDT_6A_MI2U2dM5PKxvp0B8aZVs0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});